version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    working_directory: ~/build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build base image
          command: |
            docker build -t quay.io/cybozu/ubuntu:latest -f ./base/Dockerfile .
      - run:
          name: Build dev image
          command: |
            docker build -t quay.io/cybozu/ubuntu-dev:latest -f ./dev/Dockerfile .
  push:
    docker:
      - image: docker:stable
    working_directory: ~/build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Quay.io
          command:  docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
      - run:
          name: Push base Docker image to Quay.io
          command: |
            TAG=`git describe --abbrev=0`
            docker tag quay.io/cybozu/ubuntu:latest quay.io/cybozu/ubuntu:$TAG
            docker tag quay.io/cybozu/ubuntu:$TAG quay.io/cybozu/ubuntu:18.04
            docker push quay.io/cybozu/ubuntu:$TAG
            docker push quay.io/cybozu/ubuntu:18.04
      - run:
          name: Push dev Docker image to Quay.io
          command: |
            TAG=`git describe --abbrev=0`
            docker tag quay.io/cybozu/ubuntu-dev:$TAG quay.io/cybozu/ubuntu-dev:18.04
            docker tag quay.io/cybozu/ubuntu-dev:latest quay.io/cybozu/ubuntu-dev:$TAG
            docker push quay.io/cybozu/ubuntu-dev:$TAG
            docker push quay.io/cybozu/ubuntu-dev:18.04

workflows:
  version: 2
  build:
    jobs:
      - build:
      - push:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
