version: 2.1
jobs:
  build:
    parameters:
      version:
        type: string
    working_directory: /app
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install tools
          command: |
            apk add --no-cache curl jq
      - run:
          name: Extract build targets
          working_directory: <<parameters.version>>
          command: |
            for image in ubuntu ubuntu-dev ubuntu-debug; do
                c="$(../tag_exists $image)"
                if [ "$c" = ng ]; then
                    echo $image >> BUILDS
                fi
            done
      - run:
          name: Build images
          working_directory: <<parameters.version>>
          command: |
            if [ ! -f BUILDS ]; then
                echo "nothing to build."
                exit 0
            fi
            for d in $(cat BUILDS); do
                echo
                echo "building $d ..."
                docker build -t quay.io/cybozu/${d}:latest $d
            done
      - deploy:
          name: Push Docker image to Quay.io
          working_directory: <<parameters.version>>
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
                exit 0
            fi
            if [ ! -f BUILDS ]; then
                exit 0
            fi
            docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
            for d in $(cat BUILDS); do
                echo
                echo "pushing $d ..."
                TAG=$(cat TAG)
                docker tag quay.io/cybozu/${d}:latest quay.io/cybozu/${d}:$TAG
                docker push quay.io/cybozu/${d}:$TAG
                if [ -f BRANCH ]; then
                    BRANCH=$(cat BRANCH)
                    docker tag quay.io/cybozu/${d}:$TAG quay.io/cybozu/${d}:$BRANCH
                    docker push quay.io/cybozu/${d}:$BRANCH
                fi
            done

workflows:
  version: 2
  main:
    jobs:
      - build:
          name: Build 18.04 images
          version: "18.04"
      - build:
          name: Build 20.04 images
          version: "20.04"
