name: main
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build images
    strategy:
      matrix:
        ubuntu-version: ["18.04", "20.04"]
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ${{ matrix.ubuntu-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Extract build targets
        run: |
          for image in ubuntu ubuntu-dev ubuntu-debug; do
              c="$(../tag_exists $image)"
              if [ "$c" = ng ]; then
                  echo $image >> BUILDS
              fi
          done
      - name: Build images
        run: |
          if [ ! -f BUILDS ]; then
              echo "nothing to build."
              exit 0
          fi
          for d in $(cat BUILDS); do
              echo
              echo "building $d ..."
              docker build -t quay.io/cybozu/${d}:latest ${d}
          done
      - name: Push docker images
        if: github.event_name != 'pull_request'
        run: |
          if [ ! -f BUILDS ]; then
              exit 0
          fi
          echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USER }} --password-stdin quay.io
          TAG=$(cat TAG)
          BRANCH=$(cat BRANCH)
          for d in $(cat BUILDS); do
              echo "pushing ${d} ..."
              docker tag quay.io/cybozu/${d}:latest quay.io/cybozu/${d}:$TAG
              docker push quay.io/cybozu/${d}:$TAG
              docker tag quay.io/cybozu/${d}:latest quay.io/cybozu/${d}:$BRANCH
              docker push quay.io/cybozu/${d}:$BRANCH
          done
